### PR TITLE
Explicitly reference System.*

### LINKED ISSUE #9: Rex::Powershell::Command.compress_script generates not working payloads
Rex::Powershell::Command.compress_script generates payload that are not working on win 10 1803. after some debugging i discovered that:

- the current generated payload is

`( NeW-OBJeCT iO.streAmreaDER( ( NeW-OBJeCT  Io.ComPreSsioN.dEfLATEStReAm( [SYsTEM.Io.MEMOrYstReam][coNvERT]::FROmBase64sTRinG('S03OyFdIzkzMV6hRyC8t0U3LzElVAJMFiSUZCslWMaXFqUXFMQWlSTmZyTEpmfnJiXmpeiUVJQA=') ,[sYStEM.Io.cOMpreSSiON.coMprEssIONMoDe]::decoMPrEss)) ,[systEM.TeXT.EncoDIng]::ASCii) ).reAdtoEnD( )| Write-Host`

- but the working version is

`( NeW-OBJeCT system.iO.streAmreaDER( ( NeW-OBJeCT  system.Io.ComPreSsioN.dEfLATEStReAm( [SYsTEM.Io.MEMOrYstReam][system.coNvERT]::FROmBase64sTRinG('S03OyFdIzkzMV6hRyC8t0U3LzElVAJMFiSUZCslWMaXFqUXFMQWlSTmZyTEpmfnJiXmpeiUVJQA=') ,[sYStEM.Io.cOMpreSSiON.coMprEssIONMoDe]::decoMPrEss)) ,[systEM.TeXT.EncoDIng]::ASCii) ).reAdtoEnD( )| Write-Host`

### PR DESCRIPTION
**Pull request by phra**
will fix #9

### CODE REVIEW

**Comment by busterb** [comment]
This 'rex' library is not the one that Metasploit uses however. You want https://github.com/rapid7/rex-powershell to address that.

**Comment by phra** [comment]
i will send another PR there.

**Comment by busterb** [comment]
Thanks!

**Comment by phra** [comment]
superseded by https://github.com/rapid7/rex-powershell/pull/16

**Pull request closed without merging**
